/**
 * 加载动画动词
 *
 * 用于加载状态提示（如 "Thinking...", "Analyzing..."）。
 * 支持 replace 或 append 模式的自定义动词配置。
 */

export const SPINNER_VERBS = [
  "Accomplishing",
  "Actioning",
  "Analyzing",
  "Architecting",
  "Assembling",
  "Attending",
  "Baking",
  "Beboppin",
  "Blending",
  "Brewing",
  "Building",
  "Calculating",
  "Churning",
  "Clauding",
  "Cogitating",
  "Collecting",
  "Compiling",
  "Computing",
  "Constructing",
  "Cooking",
  "Correlating",
  "Crafting",
  "Creating",
  "Crunching",
  "Debugging",
  "Decoding",
  "Decomposing",
  "Deducing",
  "Delving",
  "Deriving",
  "Designing",
  "Detecting",
  "Determining",
  "Developing",
  "Distilling",
  "Drafting",
  "Evaluating",
  "Examining",
  "Exploring",
  "Extracting",
  "Fabricating",
  "Fetching",
  "Filtering",
  "Formulating",
  "Fusing",
  "Generating",
  "Gathering",
  "Groking",
  "Harmonizing",
  "Identifying",
  "Illuminating",
  "Imagining",
  "Implementing",
  "Inferring",
  "Inspecting",
  "Installing",
  "Integrating",
  "Interpreting",
  "Investigating",
  "Iterating",
  "Linking",
  "Mapping",
  "Measuring",
  "Meditating",
  "Melding",
  "Mining",
  "Modelling",
  "Musing",
  "Navigating",
  "Observing",
  "Optimizing",
  "Orchestrating",
  "Organizing",
  "Parsing",
  "Perceiving",
  "Perfecting",
  "Performing",
  "Pondering",
  "Priming",
  "Processing",
  "Producing",
  "Probing",
  "Projecting",
  "Prototyping",
  "Puzzling",
  "Reasoning",
  "Reckoning",
  "Refactoring",
  "Refining",
  "Rendering",
  "Researching",
  "Resolving",
  "Retrieving",
  "Reviewing",
  "Revising",
  "Running",
  "Sauteed",
  "Scaffolding",
  "Scanning",
  "Searching",
  "Sequencing",
  "Shaping",
  "Sifting",
  "Simulating",
  "Sketching",
  "Solving",
  "Sorting",
  "Speculating",
  "Spinning",
  "Structuring",
  "Studying",
  "Synthesizing",
  "Testing",
  "Thinking",
  "Tinkering",
  "Transforming",
  "Translating",
  "Troubleshooting",
  "Understanding",
  "Unfolding",
  "Unpacking",
  "Unraveling",
  "Untangling",
  "Validating",
  "Verifying",
  "Vibing",
  "Visualizing",
  "Weaving",
  "Whipping",
  "Working",
  "Yielding",
  "Zigzagging",
] as const;

export type SpinnerVerb = (typeof SPINNER_VERBS)[number];

/**
 * 获取 spinner 动词列表
 * @param customVerbs 自定义动词（可选）
 * @param mode 'replace' 替换默认动词，'append' 追加到默认动词后
 */
export function getSpinnerVerbs(
  customVerbs?: string[],
  mode: "replace" | "append" = "append",
): readonly string[] {
  if (!customVerbs || customVerbs.length === 0) {
    return SPINNER_VERBS;
  }
  if (mode === "replace") {
    return customVerbs;
  }
  return [...SPINNER_VERBS, ...customVerbs];
}
