/**
 * S2 — NAME-first SendMessage resolution fallback.
 *
 * upstream addresses team members by NAME and writes to their mailbox even
 * when no running agent currently holds that name; cursor-ui-clone's
 * `lookupActiveAgent` only matches running agents, so prior to S2 a
 * SendMessage to "researcher" (when the runner had finished its turn or
 * never auto-resumed) failed with a generic "no active agent" error.
 *
 * This module provides {@link tryResolveNameFallback}: when the primary
 * `lookupActiveAgent` path returns `not_found` AND disk-sidechain recovery
 * was unavailable / declined, we try one more time with upstream-style
 * NAME-first semantics:
 *
 *  1. Lead aliases (`lead`, `team-lead`, `teamlead`) resolve to the team's
 *     `leadAgentId` — except when the caller IS the lead (then refuse:
 *     "you cannot SendMessage to yourself").
 *  2. Plain names resolve to a registered active-agent row matching the
 *     team scope, regardless of running state. Ambiguous matches (≥2
 *     same-name members in the same team) are surfaced explicitly.
 *  3. Targets that look like opaque ids (uuids, `agent-bg-…`, `lead-…`)
 *     bail out so the caller's "not found" error path stays accurate.
 *
 * The fallback intentionally does NOT spawn / resume agents — that is
 * the responsibility of disk-sidechain recovery (already attempted by
 * the caller) and the §S5 shutdown / resume slice. We only deliver the
 * envelope; if the recipient is non-running the caller surfaces a
 * "queued for next start" hint via the returned `running` flag.
 */

import type { ActiveAgent } from './types'
import { getActiveAgents } from './activeAgentRegistry'
import { getTeam } from '../tools/TeamCreateTool'

export type NameFallbackResolution =
  /** Recipient is the team's lead — write to lead mailbox key. */
  | {
      kind: 'lead'
      teamName: string
      /** {@link Team.leadAgentId} — string (the brand is only enforced on
       *  the spawn path; on the {@link Team} type the field is plain string). */
      leadAgentId: string
    }
  /** Caller IS the lead of the team — sending to "lead" is a self-send; refuse. */
  | { kind: 'self_lead'; teamName: string }
  /** Resolved to a uniquely registered team member (any status). */
  | {
      kind: 'member'
      teamName: string
      agent: ActiveAgent
    }
  /** ≥2 same-name members in the same team — caller must disambiguate. */
  | {
      kind: 'ambiguous'
      teamName: string
      agentName: string
      candidates: ActiveAgent[]
    }
  /** No team context available; cannot try NAME-mailbox semantics. */
  | { kind: 'no_team' }
  /** Target is not a plausible NAME (uuid / synthetic id / etc.) — skip. */
  | { kind: 'not_a_name' }

const LEAD_NAME_ALIASES: ReadonlySet<string> = new Set([
  'lead',
  'team-lead',
  'teamlead',
])

/**
 * Heuristic guard so we don't accidentally route opaque ids through the
 * NAME-mailbox path (which would persist a useless mailbox row keyed by
 * an id no one will ever read by name). Conservative — when in doubt,
 * return false and let the caller's not-found error fire.
 */
function isPlausibleName(s: string): boolean {
  if (!s) return false
  // Synthetic ids generated by this host
  if (/^(agent-(bg|fg)|lead)-\d+-\d+$/.test(s)) return false
  // URL-ish / scheme-ish targets are never names
  if (/[/:]/.test(s)) return false
  // uuid-like (32+ hex/dash blob)
  if (/^[0-9a-f-]{32,}$/i.test(s)) return false
  return true
}

export interface NameFallbackArgs {
  /** SendMessage `to` after parsing (no `team:` / `mailbox:` / `bridge:` prefix). */
  lookupId: string
  /** Caller's ALS `agentId` ('main' for the top-level chat session). */
  callerAgentId: string
  /** True if caller's ALS context is a spawned teammate (`ctx.teammate`). */
  callerIsTeammate: boolean
  /**
   * Resolved team scope: explicit `team_name` parameter OR caller `ctx.teamId`.
   * When absent, we cannot honour NAME-mailbox semantics.
   */
  teamHint: string | undefined
}

export function tryResolveNameFallback(args: NameFallbackArgs): NameFallbackResolution {
  const lookupId = (args.lookupId ?? '').trim()
  const lookupLower = lookupId.toLowerCase()
  const teamHint = (args.teamHint ?? '').trim()

  if (LEAD_NAME_ALIASES.has(lookupLower)) {
    if (!teamHint) return { kind: 'no_team' }
    const team = getTeam(teamHint)
    if (!team) return { kind: 'no_team' }
    // Lead = top-level chat session bound to this team and not itself a
    // spawned teammate. Mirrors {@link isCallerLead} semantics.
    const callerIsLead =
      !args.callerIsTeammate && args.callerAgentId.trim() === 'main'
    if (callerIsLead) return { kind: 'self_lead', teamName: team.teamName }
    return {
      kind: 'lead',
      teamName: team.teamName,
      leadAgentId: team.leadAgentId,
    }
  }

  if (!teamHint) return { kind: 'no_team' }
  if (!isPlausibleName(lookupId)) return { kind: 'not_a_name' }

  const candidates: ActiveAgent[] = []
  for (const agent of getActiveAgents().values()) {
    if (
      agent.name === lookupId &&
      (agent.teamName ?? '').trim() === teamHint
    ) {
      candidates.push(agent)
    }
  }

  if (candidates.length === 0) return { kind: 'not_a_name' }
  if (candidates.length === 1) {
    return { kind: 'member', teamName: teamHint, agent: candidates[0] }
  }
  return {
    kind: 'ambiguous',
    teamName: teamHint,
    agentName: lookupId,
    candidates,
  }
}
